---
  language: go
  sudo: true
  notifications:
    email: true
  go:
    - 1.x
    - tip
  services:
    - docker
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - make release
  deploy:
    provider: releases
    api_key:
      secure: P2N8Uld9jqCjNIlwiUz28XjtH2dVALnK9s8ftPuJPgUtmj4ZeFHdEIV9ujZuB9eD0jEtRFe44YzOzITylAZFxEEQxu9NbXBebLp2U4lifUlvrrPf/pIS4d2oBoIGVDvGALHS3RRZIPckyaPWbNQyrLsaPSlz7ImRyPTzjGlR1TxOOvs7SqHapQD6umNxCh6cnq07Kgkmx12k4DwaIb9ixFlKtU1ubj/HgBEBf5TuFY/y4QPneF6pS/l1QwemLBQ0f1hJ6Pj00ko8w/kysqEru37qRH1Ev1uh0zi/h95HztbNYiIGw23i3g2ojgTubgR9V5c1dDNkMynN/cwCa8k2uaTjOn5L4DBurZDnKVVNIipXySlLoda7aWMREnYjij3pSFbp6AnvsMo1SBKAeLnBEd2RivtfjxjD3rfakqpa7H8CkVruXvHSCcuctZIQw0tcQciKF3KObZWOt2LksHuRFNEQkd0FI3Al1WX01m5LEGP7LbEIzokyXbAaXHCmP7xTjh0JhvBmx/cLKQvYRNZxGtrDefc3Vuu49nldstTF6gL5PpZmiMGhZJ/dEz79QJL5AHPXM9PN4rd7we97SbHeqID//P5FDdr1j1Q0jXy4u6vaG7YdmCnmpqqn8k9fYCGVr/Tjpfdkuryk9KltaIrkZCUBMrlnbR4=
    file:
      - cross/grafctl-darwin-386
      - cross/grafctl-darwin-386.md5
      - cross/grafctl-darwin-amd64
      - cross/grafctl-darwin-amd64.md5
      - cross/grafctl-linux-386
      - cross/grafctl-linux-386.md5
      - cross/grafctl-linux-amd64
      - cross/grafctl-linux-amd64.md5
      - cross/grafctl-linux-arm
      - cross/grafctl-linux-arm.md5
      - cross/grafctl-linux-arm64
      - cross/grafctl-linux-arm64.md5
      - cross/grafctl-windows-386
      - cross/grafctl-windows-386.md5
      - cross/grafctl-windows-amd64
      - cross/grafctl-windows-amd64.md5
    skip_cleanup: true
    on:
      tags: true
