---
  language: go
  sudo: true
  notifications:
    email: true
  go:
    - 1.x
    - tip
  services:
    - docker
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - make release
  deploy:
    provider: releases
    api_key:
      secure: L7a65W70DVxSkFFPA+An40cTZN6Pi7S0qYldVNB4+qJYdFddFvA2Galjd1G+IF1Otib9op652ghIq4tbx1qjGdEohZQyiSz1aMwhQUbU1013OBEGoSGb6N+mtphW8KgAJpKm+dewQu4EYeCIJ9OUCpzwc5zuFzLEvDXlOW74pBJ4OamR0Cka69YmrNqhGQHA5hgP0kMHPPbNWyWRRD4FmF2+JButNaO35ASmq2HukEaVIsbYNBdB7POX2UUOhbQ8aEtOcaqEWRzDRJDCktwjWRXo3duxKi30eRWbNzSPYw+jgAtsZGBhlIhqVzXaRRz8ZtC8PHNyAX0fxQCI+ESEP1yFfgqckW3/72nx7gkVPL3q9CcDa5Qkg+G9tRm5D71mnc14conBHUXgpd250CRErVWaJePJhnLDaHfB5oeeyRSTAKl+8kxl3He40EQZXm+3s7Tp//NV8JyJgm6Vu1QA88MGQ+BaHyBgVxf8pCj2BDMTPhFpNSIKe5bZbVmvB8D21rEjYVLC2FQn/F7LUqaj9D3+OKtRAYV8kKK0CSIUzPTHtwCJUiPDHbFFxtWZQEBkw/30t6mN6uu2h/gecswK0BWHeeh9tJU1d4CKio33FcLwbHx8rSj4L/rSEEiCFcI3B6HxbFGMNxLKr8Xv2dPipx5QEIfg1rl01OdRIyNIHTg=
    file:
      - cross/grafctl-darwin-386
      - cross/grafctl-darwin-386.md5
      - cross/grafctl-darwin-amd64
      - cross/grafctl-darwin-amd64.md5
      - cross/grafctl-linux-386
      - cross/grafctl-linux-386.md5
      - cross/grafctl-linux-amd64
      - cross/grafctl-linux-amd64.md5
      - cross/grafctl-linux-arm
      - cross/grafctl-linux-arm.md5
      - cross/grafctl-linux-arm64
      - cross/grafctl-linux-arm64.md5
      - cross/grafctl-windows-386
      - cross/grafctl-windows-386.md5
      - cross/grafctl-windows-amd64
      - cross/grafctl-windows-amd64.md5
    skip_cleanup: true
    on:
      tags: true
