required=[
  "github.com/spf13/cobra",
  "github.com/sirupsen/logrus",
  "github.com/gosuri/uitable",
  "github.com/stretchr/testify"
]

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[prune]
  go-tests = true
  unused-packages = true
